
/* Program generated by Cbasic 4.4.0  */
#define XSCT_CBASIC

#define SCT_VERSION_4_4
#define XENABLE_VERSION_CHECK

#include "scttypes.h"
#ifdef XINCLUDE_HS_FILE
#include "go_back_n_sdl.hs"
#endif
XSYSTEMVARS
#ifdef XCTRACE
static char  xFileName[] = "C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\go_back_n_sdl.c";
#endif

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* SYSTEM go_back_n_sdl
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy,4,1,8)
******/
extern XCONST struct xSystemIdStruct ySysR_z_go_back_n_sdl;

/*****
* NEWTYPE Packet  (TYPE section)
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),122(45,40),1,9)
******/
extern tSDLStructInfo ySDL_zD_Packet;
typedef struct zD_Packet_s {
    SDL_Charstring  data;
    SDL_Integer  flag;
} zD_Packet;

/*****
* NEWTYPE frame  (TYPE section)
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),122(45,40),5,9)
******/
extern tSDLStructInfo ySDL_zE_frame;
typedef struct zE_frame_s {
    zD_Packet  info;
    SDL_Integer  seq;
    SDL_Integer  ack;
} zE_frame;

/*****
* NEWTYPE Packet  (HEADING section)
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),122(45,40),1,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_zD_Packet;
#define ySrtN_zD_Packet  (&ySrtR_zD_Packet)
#endif

#define yAss_zD_Packet(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_zD_Packet)
#define yAssF_zD_Packet(V,E,A)  yAss_zD_Packet(&(V),E,A)
#define yEq_zD_Packet(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_zD_Packet)
#define yEqF_zD_Packet(Expr1,Expr2)  yEq_zD_Packet(Expr1,Expr2)
#define yNEqF_zD_Packet(Expr1,Expr2)  ( ! yEq_zD_Packet(Expr1,Expr2) )
#define yFree_zD_Packet(P) GenericFreeSort((void **)P, (tSDLTypeInfo *)&ySDL_zD_Packet)
#ifndef ANY_zD_Packet
#define ANY_zD_Packet(R) (zD_Packet *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_zD_Packet)
#endif
#define zD3_copy(P)  P

/*****
* NEWTYPE frame  (HEADING section)
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),122(45,40),5,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_zE_frame;
#define ySrtN_zE_frame  (&ySrtR_zE_frame)
#endif

#define yAss_zE_frame(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_zE_frame)
#define yAssF_zE_frame(V,E,A)  yAss_zE_frame(&(V),E,A)
#define yEq_zE_frame(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_zE_frame)
#define yEqF_zE_frame(Expr1,Expr2)  yEq_zE_frame(Expr1,Expr2)
#define yNEqF_zE_frame(Expr1,Expr2)  ( ! yEq_zE_frame(Expr1,Expr2) )
#define yFree_zE_frame(P) GenericFreeSort((void **)P, (tSDLTypeInfo *)&ySDL_zE_frame)
#ifndef ANY_zE_frame
#define ANY_zE_frame(R) (zE_frame *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_zE_frame)
#endif
#define zE3_copy(P)  P

/*****
* BLOCK DataLink1
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\DataLink1.sbk,4,1,7)
******/
extern XCONST struct xBlockIdStruct yBloR_z0_DataLink1;

/*****
* NEWTYPE bufferType  (TYPE section)
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),116(5,25),1,9)
******/
extern tSDLGArrayInfo ySDL_z028_bufferType;

typedef struct z028_bufferType_ystruct * z028_bufferType_yptr;
typedef struct z028_bufferType_ystruct {
  z028_bufferType_yptr Suc;
  SDL_Integer Index;
  zD_Packet Data;
} z028_bufferType_yrec;
typedef struct {
  z028_bufferType_yptr First;
  z028_bufferType_yptr Last;
  int IsAssigned;
  zD_Packet Data;
} z028_bufferType;

/*****
* NEWTYPE bufferType  (HEADING section)
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),116(5,25),1,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z028_bufferType;
#define ySrtN_z028_bufferType  (&ySrtR_z028_bufferType)
#endif

#define yAss_z028_bufferType(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z028_bufferType)
#define yAssF_z028_bufferType(V,E,A)  yAss_z028_bufferType(&(V),E,A)
#define yEq_z028_bufferType(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z028_bufferType)
#define yEqF_z028_bufferType(Expr1,Expr2)  yEq_z028_bufferType(Expr1,Expr2)
#define yNEqF_z028_bufferType(Expr1,Expr2)  ( ! yEq_z028_bufferType(Expr1,Expr2) )
#define yFree_z028_bufferType(P) GenericFreeSort((void **)P, (tSDLTypeInfo *)&ySDL_z028_bufferType)
#define yExtr_z028_bufferType(V1,V2) ((zD_Packet *)GenGArray_Extract((xGArray_Type *)V1,V2,&ySDL_z028_bufferType))
#define yAddr_z028_bufferType(V1,V2) ((zD_Packet *)GenGArray_Modify((xGArray_Type *)V1,V2,&ySDL_z028_bufferType))
#ifndef ANY_z028_bufferType
#define ANY_z028_bufferType(R) (z028_bufferType *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z028_bufferType)
#endif
#define z0286_copy(P)  P

/*****
* PROCESS P1
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr,4,1,9)
******/
extern XCONST XSIGTYPE yPrsS_z02_P1[];
extern XCONST xStateIdNode yPrsT_z02_P1[];
extern XCONST struct xPrsIdStruct yPrsR_z02_P1;
#define yPrsN_z02_P1  (&yPrsR_z02_P1)
#ifdef XCOVERAGE
extern long int yPrsC_z02_P1[];
#endif
YPAD_PROTOTYPE(yPAD_z02_P1)
extern XCONST struct xSignalIdStruct ySigR_z02_P1;
#define ySigN_z02_P1  (&ySigR_z02_P1)
typedef struct {
    SIGNAL_VARS
    STARTUP_VARS
} yPDef_z02_P1;
typedef yPDef_z02_P1  *yPDP_z02_P1;
XPROCESSDEF_H(P1,"P1",z02_P1,yPAD_z02_P1,yVDef_z02_P1)
#ifndef XOPTCHAN
extern XCONST xIdNode yPrsO_z02_P1[];
#endif
#ifdef XBREAKBEFORE
#define ySym_z02_P1  53
extern char * yRef_z02_P1 (int, xSymbolType *);
#endif
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),2,1) */
    SDL_Integer z02C_next_frame_to_send;
                /* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),3,1) */
    SDL_Integer z02D_next_frame_expected;
                /* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),4,1) */
    SDL_Integer z02E_frame_expected;
                /* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),5,1) */
    SDL_Integer z02F_ack_expected;
                /* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),6,1) */
    zE_frame z02G_f1;
                /* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),6,4) */
    zE_frame z02H_f2;
                /* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),7,1) */
    SDL_Integer z02I_bufferNum;
                /* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),7,11) */
    SDL_Integer z02J_i;
                /* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),7,13) */
    SDL_Integer z02K_x;
                /* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),8,1) */
    z028_bufferType z02L_buffer;
                /* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),9,7) */
    DEF_TIMER_VAR_PARA(yTim_T1)
                /* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),10,7) */
    DEF_TIMER_VAR(yTim_T2)
} yVDef_z02_P1;
typedef yVDef_z02_P1  *yVDP_z02_P1;
extern void yFree_z02_P1 (void *);

/*****
* STATE Wait
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),131(65,50),1,1)
******/
#define z029_Wait  1
extern XCONST struct xStateIdStruct yStaR_z029_Wait;
#define yStaN_z029_Wait  (&yStaR_z029_Wait)

/*****
* TIMER T1
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),9,7)
******/
extern XCONST struct xSignalIdStruct ySigR_z02A_T1;
#define ySigN_z02A_T1  (&ySigR_z02A_T1)
typedef struct {
    TIMER_VARS
    SDL_Integer  Param1;
} yPDef_z02A_T1;
typedef yPDef_z02A_T1  *yPDP_z02A_T1;
#ifndef XNOEQTIMERFUNC
extern xbool yEqT_z02A_T1 (void *, void *);
#endif

/*****
* TIMER T2
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),10,7)
******/
extern XCONST struct xSignalIdStruct ySigR_z02B_T2;
#define ySigN_z02B_T2  (&ySigR_z02B_T2)

/*****
* DCL next_frame_to_send
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),2,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02C_next_frame_to_send;
#endif

/*****
* DCL next_frame_expected
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),3,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02D_next_frame_expected;
#endif

/*****
* DCL frame_expected
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),4,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02E_frame_expected;
#endif

/*****
* DCL ack_expected
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),5,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02F_ack_expected;
#endif

/*****
* DCL f1
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),6,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02G_f1;
#endif

/*****
* DCL f2
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),6,4)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02H_f2;
#endif

/*****
* DCL bufferNum
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),7,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02I_bufferNum;
#endif

/*****
* DCL i
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),7,11)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02J_i;
#endif

/*****
* DCL x
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),7,13)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02K_x;
#endif

/*****
* DCL buffer
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),8,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02L_buffer;
#endif

/*****
* SIGNALROUTE N11
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\DataLink1.sbk(1),122(50,60),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z03_N11[];
extern XCONST xIdNode yChaOR_z03_N11[];
extern XCONST struct xChannelIdStruct yChaR_z03_N11;
extern XCONST struct xChannelIdStruct yChaRR_z03_N11;
#define yChaN_z03_N11  (&yChaR_z03_N11)
#endif

/*****
* SIGNALROUTE D1
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\DataLink1.sbk(1),131(145,60),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z04_D1[];
extern XCONST xIdNode yChaOR_z04_D1[];
extern XCONST struct xChannelIdStruct yChaR_z04_D1;
extern XCONST struct xChannelIdStruct yChaRR_z04_D1;
#define yChaN_z04_D1  (&yChaR_z04_D1)
#endif

/*****
* BLOCK DataLink2
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\DataLink2.sbk,4,1,7)
******/
extern XCONST struct xBlockIdStruct yBloR_z1_DataLink2;

/*****
* SIGNALROUTE D2
* <<SYSTEM go_back_n_sdl/BLOCK DataLink2>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\DataLink2.sbk(1),182(52,52),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z13_D2[];
extern XCONST xIdNode yChaOR_z13_D2[];
extern XCONST struct xChannelIdStruct yChaR_z13_D2;
extern XCONST struct xChannelIdStruct yChaRR_z13_D2;
#define yChaN_z13_D2  (&yChaR_z13_D2)
#endif

/*****
* CHANNEL N1
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),155(32,87),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z2_N1[];
extern XCONST xIdNode yChaOR_z2_N1[];
extern XCONST struct xChannelIdStruct yChaR_z2_N1;
extern XCONST struct xChannelIdStruct yChaRR_z2_N1;
#define yChaN_z2_N1  (&yChaR_z2_N1)
#ifdef XMULTIPLESYSTEMS
extern XCONST xIdNode yConnIn_go_back_n_sdl_N1[];
extern XCONST xIdNode yConnOut_go_back_n_sdl_N1[];
extern XCONST struct xChannelIdStruct yGateIn_go_back_n_sdl_N1;
extern XCONST struct xChannelIdStruct yGateOut_go_back_n_sdl_N1;
#endif
#endif

/*****
* CHANNEL D
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),131(96,87),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z3_D[];
extern XCONST xIdNode yChaOR_z3_D[];
extern XCONST struct xChannelIdStruct yChaR_z3_D;
extern XCONST struct xChannelIdStruct yChaRR_z3_D;
#define yChaN_z3_D  (&yChaR_z3_D)
#endif

/*****
* SIGNAL ToDatalink1
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),1,8)
******/
extern XCONST struct xSignalIdStruct ySigR_z5_ToDatalink1;
#define ySigN_z5_ToDatalink1  (&ySigR_z5_ToDatalink1)
typedef struct {
    SIGNAL_VARS
    zE_frame  Param1;
} yPDef_z5_ToDatalink1;
typedef yPDef_z5_ToDatalink1  *yPDP_z5_ToDatalink1;
#ifdef XFREESIGNALFUNCS
extern void yFree_z5_ToDatalink1 (void *SVarP);
#endif

/*****
* SIGNAL ToDataLink2
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),1,27)
******/
extern XCONST struct xSignalIdStruct ySigR_z6_ToDataLink2;
#define ySigN_z6_ToDataLink2  (&ySigR_z6_ToDataLink2)
typedef struct {
    SIGNAL_VARS
    zE_frame  Param1;
} yPDef_z6_ToDataLink2;
typedef yPDef_z6_ToDataLink2  *yPDP_z6_ToDataLink2;
#ifdef XFREESIGNALFUNCS
extern void yFree_z6_ToDataLink2 (void *SVarP);
#endif

/*****
* SIGNAL FromNetwork1
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),1,46)
******/
extern XCONST struct xSignalIdStruct ySigR_z7_FromNetwork1;
#define ySigN_z7_FromNetwork1  (&ySigR_z7_FromNetwork1)
typedef struct {
    SIGNAL_VARS
    zD_Packet  Param1;
} yPDef_z7_FromNetwork1;
typedef yPDef_z7_FromNetwork1  *yPDP_z7_FromNetwork1;
#ifdef XFREESIGNALFUNCS
extern void yFree_z7_FromNetwork1 (void *SVarP);
#endif

/*****
* SIGNAL FromNetwork2
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),2,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z8_FromNetwork2;
#define ySigN_z8_FromNetwork2  (&ySigR_z8_FromNetwork2)
typedef struct {
    SIGNAL_VARS
    zD_Packet  Param1;
} yPDef_z8_FromNetwork2;
typedef yPDef_z8_FromNetwork2  *yPDP_z8_FromNetwork2;
#ifdef XFREESIGNALFUNCS
extern void yFree_z8_FromNetwork2 (void *SVarP);
#endif

/*****
* SIGNAL AckToDataLink1
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),2,22)
******/
extern XCONST struct xSignalIdStruct ySigR_z9_AckToDataLink1;
#define ySigN_z9_AckToDataLink1  (&ySigR_z9_AckToDataLink1)
typedef struct {
    SIGNAL_VARS
    zE_frame  Param1;
} yPDef_z9_AckToDataLink1;
typedef yPDef_z9_AckToDataLink1  *yPDP_z9_AckToDataLink1;
#ifdef XFREESIGNALFUNCS
extern void yFree_z9_AckToDataLink1 (void *SVarP);
#endif

/*****
* SIGNAL AckToDataLink2
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),2,44)
******/
extern XCONST struct xSignalIdStruct ySigR_zA_AckToDataLink2;
#define ySigN_zA_AckToDataLink2  (&ySigR_zA_AckToDataLink2)
typedef struct {
    SIGNAL_VARS
    zE_frame  Param1;
} yPDef_zA_AckToDataLink2;
typedef yPDef_zA_AckToDataLink2  *yPDP_zA_AckToDataLink2;
#ifdef XFREESIGNALFUNCS
extern void yFree_zA_AckToDataLink2 (void *SVarP);
#endif

/*****
* SIGNAL ToNetwork1
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),3,1)
******/
extern XCONST struct xSignalIdStruct ySigR_zB_ToNetwork1;
#define ySigN_zB_ToNetwork1  (&ySigR_zB_ToNetwork1)
typedef struct {
    SIGNAL_VARS
    zD_Packet  Param1;
} yPDef_zB_ToNetwork1;
typedef yPDef_zB_ToNetwork1  *yPDP_zB_ToNetwork1;
#ifdef XFREESIGNALFUNCS
extern void yFree_zB_ToNetwork1 (void *SVarP);
#endif

/*****
* SIGNAL ToNetwork2
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),3,20)
******/
extern XCONST struct xSignalIdStruct ySigR_zC_ToNetwork2;
#define ySigN_zC_ToNetwork2  (&ySigR_zC_ToNetwork2)
typedef struct {
    SIGNAL_VARS
    zD_Packet  Param1;
} yPDef_zC_ToNetwork2;
typedef yPDef_zC_ToNetwork2  *yPDP_zC_ToNetwork2;
#ifdef XFREESIGNALFUNCS
extern void yFree_zC_ToNetwork2 (void *SVarP);
#endif

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/

/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* SYSTEM go_back_n_sdl
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy,4,1,8)
******/
XCONST struct xSystemIdStruct ySysR_z_go_back_n_sdl = {xSystemEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&xSymbolTableIdRec, "go_back_n_sdl" XCOMMON_EXTRAS,
  (xIdNode *)0, (xPrdIdNode *)0, (xSystemIdNode)0 xTrace(-1) xGRTrace(-1)
  xMSCETrace(-1) XSYS_EXTRAS};

/*****
* ENV
******/
#ifndef XMULTIPLESYSTEMS
#ifndef XOPTCHAN
xIdNode yEnvO_env[] = {(xIdNode)&yChaRR_z2_N1, (xIdNode)&yChaRR_z3_D,
  (xIdNode)0  XTRACHANNELLIST};
#endif
#endif

/*****
* NEWTYPE Packet  (BODY section)
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),122(45,40),1,9)
******/

/* *** Packet *** */
static tSDLFieldInfo fSDL_zD_Packet[] = {
  {(tSDLTypeInfo *)&ySDL_SDL_Charstring  T_SDL_Names("data"),
    xOffsetOf(zD_Packet, data), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("flag"),
    xOffsetOf(zD_Packet, flag), 0}
};
tSDLStructInfo ySDL_zD_Packet = {type_SDL_Struct, 7, (xptrint)sizeof(zD_Packet)
  T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE T_SDL_Names("Packet")
  xRaWF((xIdNode)&ySysR_z_go_back_n_sdl) xRaWF(&ySrtR_zD_Packet),
  fSDL_zD_Packet, 2};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_zD_Packet = {xSortEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "Packet" XCOMMON_EXTRAS xFreF(0)
  xAssF(yAss_zD_Packet) xEqF(yEq_zD_Packet) xTestF(0),
  (xptrint)sizeof(zD_Packet), xStruct, (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0,
  0 xRaWF((tSDLTypeInfo *)&ySDL_zD_Packet) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_zD9_data = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySrtR_zD_Packet, "data" XCOMMON_EXTRAS,
  &xSrtR_SDL_Charstring, (tSDLTypeInfo *)&ySDL_SDL_Charstring,
  xOffsetOf(zD_Packet, data), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_zDA_flag = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySrtR_zD_Packet, "flag" XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer, xOffsetOf(zD_Packet,
  flag), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE frame  (BODY section)
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),122(45,40),5,9)
******/

/* *** frame *** */
static tSDLFieldInfo fSDL_zE_frame[] = {
  {(tSDLTypeInfo *)&ySDL_zD_Packet  T_SDL_Names("info"),
    xOffsetOf(zE_frame, info), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("seq"),
    xOffsetOf(zE_frame, seq), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("ack"),
    xOffsetOf(zE_frame, ack), 0}
};
tSDLStructInfo ySDL_zE_frame = {type_SDL_Struct, 7, (xptrint)sizeof(zE_frame)
  T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE T_SDL_Names("frame")
  xRaWF((xIdNode)&ySysR_z_go_back_n_sdl) xRaWF(&ySrtR_zE_frame), fSDL_zE_frame,
  3};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_zE_frame = {xSortEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&ySysR_z_go_back_n_sdl, "frame" XCOMMON_EXTRAS xFreF(0)
  xAssF(yAss_zE_frame) xEqF(yEq_zE_frame) xTestF(0), (xptrint)sizeof(zE_frame),
  xStruct, (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_zE_frame) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_zEB_info = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySrtR_zE_frame, "info" XCOMMON_EXTRAS,
  &ySrtR_zD_Packet, (tSDLTypeInfo *)&ySDL_zD_Packet, xOffsetOf(zE_frame, info),
  (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_zEC_seq = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySrtR_zE_frame, "seq" XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer, xOffsetOf(zE_frame,
  seq), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_zED_ack = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySrtR_zE_frame, "ack" XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer, xOffsetOf(zE_frame,
  ack), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* BLOCK DataLink1
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\DataLink1.sbk,4,1,7)
******/
XCONST struct xBlockIdStruct yBloR_z0_DataLink1 = {xBlockEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "DataLink1" XCOMMON_EXTRAS,
  (xBlockIdNode)0, (xIdNode *)0, (xPrdIdNode *)0, (xViewListRec *)0,
  (xViewIndexRec *)0, 1 xTrace(-1) xGRTrace(-1) xMSCETrace(-1) xMSCETrace(0)
  XBLO_EXTRAS};
#ifndef XOPTCHAN
XCONST xIdNode yChaOR_z2_N1[] = {(xIdNode)&yChaRR_z03_N11, (xIdNode)0};
XCONST xIdNode yChaOR_z3_D[] = {(xIdNode)&yChaRR_z04_D1, (xIdNode)0};
#endif

/*****
* NEWTYPE bufferType  (BODY section)
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),116(5,25),1,9)
******/

/* *** bufferType *** */
tSDLGArrayInfo ySDL_z028_bufferType = {type_SDL_GArray, 15,
  (xptrint)sizeof(z028_bufferType) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("bufferType") xRaWF((xIdNode)&yPrsR_z02_P1)
  xRaWF(&ySrtR_z028_bufferType), (tSDLTypeInfo *)&ySDL_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_zD_Packet, (xptrint)sizeof(z028_bufferType_yrec),
  xOffsetOf(z028_bufferType_yrec, Index), xOffsetOf(
  z028_bufferType_yrec, Data), xOffsetOf(z028_bufferType, Data)};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z028_bufferType = {xSortEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "bufferType" XCOMMON_EXTRAS xFreF(0)
  xAssF(yAss_z028_bufferType) xEqF(yEq_z028_bufferType) xTestF(0),
  (xptrint)sizeof(z028_bufferType), xGArray, &ySrtR_zD_Packet,
  &xSrtR_SDL_Integer, (long int)xOffsetOf(z028_bufferType_yrec, Data),
  (long int)sizeof(z028_bufferType_yrec), (long int)xOffsetOf(
  z028_bufferType_yrec, Index), (long int)xOffsetOf(z028_bufferType, Data)
  xRaWF((tSDLTypeInfo *)&ySDL_z028_bufferType) XSRT_EXTRAS};
#endif

/*****
* PROCESS P1
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr,4,1,9)
******/
#ifdef XCOVERAGE
long int yPrsC_z02_P1[ySym_z02_P1+1];
#endif
XCONST XSIGTYPE yPrsS_z02_P1[] = {SIGNAL_NAME(FromNetwork1,
  &ySigR_z7_FromNetwork1), SIGNAL_NAME(ToDatalink1, &ySigR_z5_ToDatalink1),
  SIGNAL_NAME(AckToDataLink1, &ySigR_z9_AckToDataLink1), SIGNAL_NAME(T1,
  &ySigR_z02A_T1), SIGNAL_NAME(T2, &ySigR_z02B_T2), (XSIGTYPE)0};
XCONST xStateIdNode yPrsT_z02_P1[] = {&xStartStateIdRec, &yStaR_z029_Wait};
static XPRSNODE yPrsA_z02_P1 = (XPRSNODE)0;
static XPRSNODE yPrsB_z02_P1 = (XPRSNODE)0;
XCONST struct xPrsIdStruct yPrsR_z02_P1 = {xProcessEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&yBloR_z0_DataLink1, "P1" XCOMMON_EXTRAS, yPrsT_z02_P1,
  yPrsS_z02_P1 xService(0) xOptChan(yPrsO_z02_P1), -1 xNrInst(1) xNrInst(1),
  &yPrsB_z02_P1, (xptrint)sizeof(yVDef_z02_P1)
  xPrsPrioPar(xDefaultPrioProcess), &yPrsA_z02_P1 xTrace(-1) xGRTrace(-1)
  xBreakB(yRef_z02_P1) xBreakB(ySym_z02_P1) xBreakB(5) xMSCETrace(-1)
  xCoverage(yPrsC_z02_P1) xCoverage(0) xCoverage(0), yPAD_z02_P1, yFree_z02_P1,
  (xPrsIdNode)0, (xPrdIdNode *)0, (xBlockIdNode)0
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr,4,1,9)")
  xThreadName(0) xThreadName(0) XPRS_EXTRAS(z02_P1)};
static xSignalNode ySigA_z02_P1 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z02_P1 = {xStartUpSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_DataLink1 xIdNames("-") XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z02_P1), &ySigA_z02_P1, 0 xFreS(0)
  SIGCODE(STARTUPSIGNAL)
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr,4,1,9)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
XPROCESSDEF_C(P1,"P1",z02_P1,yPAD_z02_P1,yVDef_z02_P1)
#ifndef XOPTCHAN
XCONST xIdNode yPrsO_z02_P1[] = {(xIdNode)&yChaR_z03_N11,
  (xIdNode)&yChaR_z04_D1, (xIdNode)0};
#endif
void yFree_z02_P1(void *yVarP)
{
  yFree_z028_bufferType((void **)&((yVDef_z02_P1 *)yVarP)->z02L_buffer);
  yFree_zE_frame((void **)&((yVDef_z02_P1 *)yVarP)->z02H_f2);
  yFree_zE_frame((void **)&((yVDef_z02_P1 *)yVarP)->z02G_f1);
}

/*+++++
* GR ref function for process P1
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr,4,1,11)
++++++*/
#ifdef XBREAKBEFORE
char * yRef_z02_P1 (int SymbolNo, xSymbolType *SymbolType)
{
  switch (SymbolNo) {
    case 0: *SymbolType = xsStart;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),122(70,5),1,1)";
    case 1: *SymbolType = xsInput;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),143(5,60),1,1)";
    case 2: *SymbolType = xsInput;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),353(120,60),1,1)";
    case 3: *SymbolType = xsInput;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),473(160,60),1,1)";
    case 4: *SymbolType = xsInput;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),281(65,65),1,1)";
    case 5: *SymbolType = xsInput;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),458(95,65),1,1)";
    case 6: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),125(60,20),1,1)";
    case 7: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),125(60,20),2,1)";
    case 8: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),125(60,20),3,1)";
    case 9: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),125(60,20),4,1)";
    case 10: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),125(60,20),5,1)";
    case 11: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),125(60,20),6,1)";
    case 12: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),131(65,50),1,1)";
    case 13: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),224(5,75),1,1)";
    case 14: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),230(5,90),1,1)";
    case 15: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),230(5,90),2,1)";
    case 16: *SymbolType = xsDecision;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),245(5,105),1,1)";
    case 17: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),254(15,120),1,1)";
    case 18: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),260(40,120),1,1)";
    case 19: *SymbolType = xsOutput;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),269(15,135),1,1)";
    case 20: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),278(5,150),1,1)";
    case 21: *SymbolType = xsSet;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),278(5,150),2,1)";
    case 22: *SymbolType = xsReset;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),278(5,150),4,1)";
    case 23: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),314(15,180),1,1)";
    case 24: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),356(120,75),1,1)";
    case 25: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),356(120,75),2,1)";
    case 26: *SymbolType = xsDecision;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),362(120,90),1,1)";
    case 27: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),374(145,90),1,1)";
    case 28: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),365(110,105),1,1)";
    case 29: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),365(110,105),2,1)";
    case 30: *SymbolType = xsDecision;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),395(110,120),1,1)";
    case 31: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),401(115,135),1,1)";
    case 32: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),404(145,135),1,1)";
    case 33: *SymbolType = xsOutput;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),413(115,150),1,1)";
    case 34: *SymbolType = xsSet;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),422(105,165),1,1)";
    case 35: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),548(105,185),1,1)";
    case 36: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),428(115,205),1,1)";
    case 37: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),479(160,75),1,1)";
    case 38: *SymbolType = xsDecision;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),488(160,105),1,1)";
    case 39: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),491(160,120),1,1)";
    case 40: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),512(160,150),1,1)";
    case 41: *SymbolType = xsOutput;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),518(160,170),1,1)";
    case 42: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),530(155,185),1,1)";
    case 43: *SymbolType = xsReset;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),530(155,185),3,1)";
    case 44: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),536(160,210),1,1)";
    case 45: *SymbolType = xsDecision;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),287(55,80),1,1)";
    case 46: *SymbolType = xsOutput;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),293(65,95),1,1)";
    case 47: *SymbolType = xsSet;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),449(65,110),1,1)";
    case 48: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),296(70,130),1,1)";
    case 49: *SymbolType = xsDecision;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),320(65,150),1,1)";
    case 50: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),326(60,165),1,1)";
    case 51: *SymbolType = xsReset;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),332(60,180),1,1)";
    case 52: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),335(60,195),1,1)";
    case 53: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),542(70,210),1,1)";
    default : *SymbolType = xsNoSuchSymbolType; return "";
  }
}
#endif

/*+++++
* Function for process P1
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr,4,1,11)
++++++*/
YPAD_FUNCTION(yPAD_z02_P1)
{
  YPAD_YSVARP
  YPAD_YVARP(yVDef_z02_P1)
  YPAD_TEMP_VARS
#ifdef XTRACE
  SDL_Boolean yDcn_SDL_Boolean;
#endif
  YPRSNAME_VAR("P1")

  BEGIN_PAD(yVDef_z02_P1)

  LOOP_LABEL
  switch (yVarP->RestartAddress) {

/*-----
* START
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),122(70,5),1,1)
------*/
  case 0:
    BEGIN_START_TRANSITION(yPDef_z02_P1)
    XAT_FIRST_SYMBOL(0)
    GenericDefault((void *)&yVarP->z02L_buffer,
      (tSDLTypeInfo *)&ySDL_z028_bufferType);
    INIT_TIMER_VAR_PARA(yTim_T1)
    INIT_TIMER_VAR(yTim_T2)
    XBETWEEN_SYMBOLS(6, 873)

/*-----
* ASSIGNMENT next_frame_to_send := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),125(60,20),1,1)
------*/
#ifdef XCASELABELS
  case 6:
#endif
    yAssF_SDL_Integer(yVarP->z02C_next_frame_to_send, SDL_INTEGER_LIT(0),
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("next_frame_to_send := ", &(yVarP->z02C_next_frame_to_send),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "next_frame_to_send := ", &(yVarP->
      z02C_next_frame_to_send), (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(7, 892)

/*-----
* ASSIGNMENT next_frame_expected := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),125(60,20),2,1)
------*/
#ifdef XCASELABELS
  case 7:
#endif
    yAssF_SDL_Integer(yVarP->z02D_next_frame_expected, SDL_INTEGER_LIT(0),
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("next_frame_expected := ", &(yVarP->z02D_next_frame_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "next_frame_expected := ", &(yVarP->
      z02D_next_frame_expected), (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(8, 911)

/*-----
* ASSIGNMENT frame_expected := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),125(60,20),3,1)
------*/
#ifdef XCASELABELS
  case 8:
#endif
    yAssF_SDL_Integer(yVarP->z02E_frame_expected, SDL_INTEGER_LIT(0),
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("frame_expected := ", &(yVarP->z02E_frame_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "frame_expected := ", &(yVarP->z02E_frame_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(9, 930)

/*-----
* ASSIGNMENT ack_expected := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),125(60,20),4,1)
------*/
#ifdef XCASELABELS
  case 9:
#endif
    yAssF_SDL_Integer(yVarP->z02F_ack_expected, SDL_INTEGER_LIT(0),
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("ack_expected := ", &(yVarP->z02F_ack_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "ack_expected := ", &(yVarP->z02F_ack_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(10, 949)

/*-----
* ASSIGNMENT bufferNum := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),125(60,20),5,1)
------*/
#ifdef XCASELABELS
  case 10:
#endif
    yAssF_SDL_Integer(yVarP->z02I_bufferNum, SDL_INTEGER_LIT(0),
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("bufferNum := ", &(yVarP->z02I_bufferNum),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "bufferNum := ", &(yVarP->z02I_bufferNum),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(11, 968)

/*-----
* ASSIGNMENT i := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),125(60,20),6,1)
------*/
#ifdef XCASELABELS
  case 11:
#endif
    yAssF_SDL_Integer(yVarP->z02J_i, SDL_INTEGER_LIT(1), XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("i := ", &(yVarP->z02J_i), (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "i := ", &(yVarP->z02J_i),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_SYMBOLS(12, 985)

/*-----
* NEXTSTATE Wait
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),131(65,50),1,1)
------*/
#ifdef XCASELABELS
  case 12:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(Wait, z029_Wait, "Wait")

/*-----
* INPUT FromNetwork1
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),143(5,60),1,1)
------*/
  case 1:
    XDEBUG_LABEL(Wait_FromNetwork1)
    XAT_FIRST_SYMBOL(1)
    XOS_TRACE_INPUT("FromNetwork1")
#ifdef XVALIDATOR_LIB
    yAssF_zD_Packet((* yAddr_z028_bufferType(&(yVarP->z02L_buffer), &(yVarP->
      z02C_next_frame_to_send))), &(((yPDef_z7_FromNetwork1 *)ySVarP)->Param1),
      XASS_MR_ASS_FR);
#else
    yAssF_zD_Packet((* yAddr_z028_bufferType(&(yVarP->z02L_buffer), &(yVarP->
      z02C_next_frame_to_send))), &(((yPDef_z7_FromNetwork1 *)ySVarP)->Param1),
      XASS_AR_ASS_FR);
#ifdef XMONITOR
    memset(&(((yPDef_z7_FromNetwork1 *)ySVarP)->Param1), 0,
      ySDL_zD_Packet.SortSize);
#endif
#endif
    XBETWEEN_SYMBOLS(13, 1018)

/*-----
* ASSIGNMENT bufferNum := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),224(5,75),1,1)
------*/
#ifdef XCASELABELS
  case 13:
#endif
    yAssF_SDL_Integer(yVarP->z02I_bufferNum, xPlus_SDL_Integer(yVarP->
      z02I_bufferNum, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("bufferNum := ", &(yVarP->z02I_bufferNum),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "bufferNum := ", &(yVarP->z02I_bufferNum),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_SYMBOLS(14, 1037)

/*-----
* ASSIGNMENT f1... := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),230(5,90),1,1)
------*/
#ifdef XCASELABELS
  case 14:
#endif
    yAssF_zD_Packet(yVarP->z02G_f1.info, yExtr_z028_bufferType(&(yVarP->
      z02L_buffer), &(yVarP->z02C_next_frame_to_send)), XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("f1... := ", &(yVarP->z02G_f1.info),
      (tSDLTypeInfo *)&ySDL_zD_Packet);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "f1... := ", &(yVarP->z02G_f1.info),
      (tSDLTypeInfo *)&ySDL_zD_Packet);
#endif
    XBETWEEN_STMTS(15, 1056)

/*-----
* ASSIGNMENT f1... := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),230(5,90),2,1)
------*/
#ifdef XCASELABELS
  case 15:
#endif
    yAssF_SDL_Integer(yVarP->z02G_f1.seq, yVarP->z02C_next_frame_to_send,
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("f1... := ", &(yVarP->z02G_f1.seq),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "f1... := ", &(yVarP->z02G_f1.seq),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_SYMBOLS(16, 1075)

/*-----
* DECISION
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),245(5,105),1,1)
------*/
#ifdef XCASELABELS
  case 16:
#endif
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yEqF_SDL_Integer(yVarP->
      z02E_frame_expected, SDL_INTEGER_LIT(0)), XASS_MR_ASS_FR);
    xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
    xMSCEDecision(VarP, &(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    if (yDcn_SDL_Boolean) {
#else
    if (yEqF_SDL_Integer(yVarP->z02E_frame_expected, SDL_INTEGER_LIT(0))) {
#endif
      XBETWEEN_SYMBOLS(17, 1095)

/*-----
* ASSIGNMENT f1... := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),254(15,120),1,1)
------*/
#ifdef XCASELABELS
    case 17:
#endif
      yAssF_SDL_Integer(yVarP->z02G_f1.ack, SDL_INTEGER_LIT(7), XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("f1... := ", &(yVarP->z02G_f1.ack),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign(VarP, "f1... := ", &(yVarP->z02G_f1.ack),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    } else {
      XBETWEEN_SYMBOLS(18, 1114)

/*-----
* ASSIGNMENT f1... := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),260(40,120),1,1)
------*/
#ifdef XCASELABELS
    case 18:
#endif
      yAssF_SDL_Integer(yVarP->z02G_f1.ack, xMinus_SDL_Integer(yVarP->
        z02E_frame_expected, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("f1... := ", &(yVarP->z02G_f1.ack),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign(VarP, "f1... := ", &(yVarP->z02G_f1.ack),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    }
    XBETWEEN_SYMBOLS(19, 1134)

/*-----
* OUTPUT ToDataLink2
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),269(15,135),1,1)
------*/
#ifdef XCASELABELS
  case 19:
#endif
    ALLOC_SIGNAL_PAR(ToDataLink2, ySigN_z6_ToDataLink2, xNotDefPId,
      yPDef_z6_ToDataLink2)
    SIGNAL_ALLOC_ERROR
    yAssF_zE_frame(((yPDef_z6_ToDataLink2 *)OUTSIGNAL_DATA_PTR)->Param1,
      &(yVarP->z02G_f1), XASS_MR_ASS_NF);
    SDL_2OUTPUT_NO_TO(xDefaultPrioSignal, (xIdNode *)0, ToDataLink2,
      ySigN_z6_ToDataLink2, xNotDefPId, sizeof(yPDef_z6_ToDataLink2),
      "ToDataLink2")
    SIGNAL_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS(20, 1152)

/*-----
* ASSIGNMENT next_frame_to_send := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),278(5,150),1,1)
------*/
#ifdef XCASELABELS
  case 20:
#endif
    yAssF_SDL_Integer(yVarP->z02C_next_frame_to_send, xPlus_SDL_Integer(yVarP->
      z02C_next_frame_to_send, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("next_frame_to_send := ", &(yVarP->z02C_next_frame_to_send),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "next_frame_to_send := ", &(yVarP->
      z02C_next_frame_to_send), (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(21, 1171)

/*-----
* SET T1
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),278(5,150),2,1)
------*/
#ifdef XCASELABELS
  case 21:
#endif
    ALLOC_TIMER_SIGNAL_PAR(T1, ySigN_z02A_T1, yPDef_z02A_T1)
    TIMER_SIGNAL_ALLOC_ERROR
    yAssF_SDL_Integer(((yPDef_z02A_T1 *)TIMER_DATA_PTR)->Param1, yVarP->
      z02C_next_frame_to_send, XASS_MR_ASS_NF);
    SDL_SET_DUR_WITH_PARA(xPlus_SDL_Time(SDL_NOW,
      SDL_DURATION_LIT(100.0, 100, 0)), SDL_DURATION_LIT(100.0, 100, 0), T1,
      ySigN_z02A_T1, yPDef_z02A_T1, yEqT_z02A_T1, yTim_T1, "T1")
    TIMER_SIGNAL_ALLOC_ERROR_END
    XBETWEEN_STMTS(22, 1188)

/*-----
* RESET T2
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),278(5,150),4,1)
------*/
#ifdef XCASELABELS
  case 22:
#endif
    SDL_RESET(T2, ySigN_z02B_T2, yTim_T2, "T2")
    XBETWEEN_SYMBOLS(23, 1198)

/*-----
* NEXTSTATE Wait
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),314(15,180),1,1)
------*/
#ifdef XCASELABELS
  case 23:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(Wait, z029_Wait, "Wait")

/*-----
* INPUT T1
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),353(120,60),1,1)
------*/
  case 2:
    XDEBUG_LABEL(Wait_T1)
    XAT_FIRST_SYMBOL(2)
    XOS_TRACE_INPUT("T1")
    INPUT_TIMER_VAR_PARA(yTim_T1)
    yAssF_SDL_Integer(yVarP->z02K_x, ((yPDef_z02A_T1 *)ySVarP)->Param1,
      XASS_AR_ASS_FR);
    XBETWEEN_SYMBOLS(24, 1221)

/*-----
* ASSIGNMENT next_frame_to_send := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),356(120,75),1,1)
------*/
#ifdef XCASELABELS
  case 24:
#endif
    yAssF_SDL_Integer(yVarP->z02C_next_frame_to_send, yVarP->z02F_ack_expected,
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("next_frame_to_send := ", &(yVarP->z02C_next_frame_to_send),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "next_frame_to_send := ", &(yVarP->
      z02C_next_frame_to_send), (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(25, 1240)

/*-----
* ASSIGNMENT i := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),356(120,75),2,1)
------*/
#ifdef XCASELABELS
  case 25:
#endif
    yAssF_SDL_Integer(yVarP->z02J_i, SDL_INTEGER_LIT(1), XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("i := ", &(yVarP->z02J_i), (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "i := ", &(yVarP->z02J_i),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif

  L_grst12:;
    XBETWEEN_SYMBOLS(26, 1259)

/*-----
* DECISION
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),362(120,90),1,1)
------*/
#ifdef XCASELABELS
  case 26:
#endif
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, xLE_SDL_Integer(yVarP->z02J_i, yVarP->
      z02I_bufferNum), XASS_MR_ASS_FR);
    xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
    xMSCEDecision(VarP, &(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    if (yDcn_SDL_Boolean) {
#else
    if (xLE_SDL_Integer(yVarP->z02J_i, yVarP->z02I_bufferNum)) {
#endif
      XBETWEEN_SYMBOLS(28, 1279)

/*-----
* ASSIGNMENT f1... := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),365(110,105),1,1)
------*/
#ifdef XCASELABELS
    case 28:
#endif
      yAssF_zD_Packet(yVarP->z02G_f1.info, yExtr_z028_bufferType(&(yVarP->
        z02L_buffer), &(yVarP->z02C_next_frame_to_send)), XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("f1... := ", &(yVarP->z02G_f1.info),
        (tSDLTypeInfo *)&ySDL_zD_Packet);
#endif
#ifdef XMSCE
      xMSCEAssign(VarP, "f1... := ", &(yVarP->z02G_f1.info),
        (tSDLTypeInfo *)&ySDL_zD_Packet);
#endif
      XBETWEEN_STMTS(29, 1298)

/*-----
* ASSIGNMENT f1... := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),365(110,105),2,1)
------*/
#ifdef XCASELABELS
    case 29:
#endif
      yAssF_SDL_Integer(yVarP->z02G_f1.seq, yVarP->z02C_next_frame_to_send,
        XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("f1... := ", &(yVarP->z02G_f1.seq),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign(VarP, "f1... := ", &(yVarP->z02G_f1.seq),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
      XBETWEEN_SYMBOLS(30, 1317)

/*-----
* DECISION
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),395(110,120),1,1)
------*/
#ifdef XCASELABELS
    case 30:
#endif
#ifdef XTRACE
      yAssF_SDL_Boolean(yDcn_SDL_Boolean, yEqF_SDL_Integer(yVarP->
        z02E_frame_expected, SDL_INTEGER_LIT(0)), XASS_MR_ASS_FR);
      xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
      xMSCEDecision(VarP, &(yDcn_SDL_Boolean),
        (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
      if (yDcn_SDL_Boolean) {
#else
      if (yEqF_SDL_Integer(yVarP->z02E_frame_expected, SDL_INTEGER_LIT(0))) {
#endif
        XBETWEEN_SYMBOLS(31, 1338)

/*-----
* ASSIGNMENT f1... := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),401(115,135),1,1)
------*/
#ifdef XCASELABELS
      case 31:
#endif
        yAssF_SDL_Integer(yVarP->z02G_f1.ack, SDL_INTEGER_LIT(7),
          XASS_MR_ASS_FR);
#ifdef XTRACE
        xTraceAssign("f1... := ", &(yVarP->z02G_f1.ack),
          (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
        xMSCEAssign(VarP, "f1... := ", &(yVarP->z02G_f1.ack),
          (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
      } else {
        XBETWEEN_SYMBOLS(32, 1358)

/*-----
* ASSIGNMENT f1... := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),404(145,135),1,1)
------*/
#ifdef XCASELABELS
      case 32:
#endif
        yAssF_SDL_Integer(yVarP->z02G_f1.ack, xMinus_SDL_Integer(yVarP->
          z02E_frame_expected, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
        xTraceAssign("f1... := ", &(yVarP->z02G_f1.ack),
          (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
        xMSCEAssign(VarP, "f1... := ", &(yVarP->z02G_f1.ack),
          (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
      }
      XBETWEEN_SYMBOLS(33, 1378)

/*-----
* OUTPUT ToDataLink2
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),413(115,150),1,1)
------*/
#ifdef XCASELABELS
    case 33:
#endif
      ALLOC_SIGNAL_PAR(ToDataLink2, ySigN_z6_ToDataLink2, xNotDefPId,
        yPDef_z6_ToDataLink2)
      SIGNAL_ALLOC_ERROR
      yAssF_zE_frame(((yPDef_z6_ToDataLink2 *)OUTSIGNAL_DATA_PTR)->Param1,
        &(yVarP->z02G_f1), XASS_MR_ASS_NF);
      SDL_2OUTPUT_NO_TO(xDefaultPrioSignal, (xIdNode *)0, ToDataLink2,
        ySigN_z6_ToDataLink2, xNotDefPId, sizeof(yPDef_z6_ToDataLink2),
        "ToDataLink2")
      SIGNAL_ALLOC_ERROR_END
      XBETWEEN_SYMBOLS(34, 1396)

/*-----
* SET T1
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),422(105,165),1,1)
------*/
#ifdef XCASELABELS
    case 34:
#endif
      ALLOC_TIMER_SIGNAL_PAR(T1, ySigN_z02A_T1, yPDef_z02A_T1)
      TIMER_SIGNAL_ALLOC_ERROR
      yAssF_SDL_Integer(((yPDef_z02A_T1 *)TIMER_DATA_PTR)->Param1, yVarP->
        z02C_next_frame_to_send, XASS_MR_ASS_NF);
      SDL_SET_DUR_WITH_PARA(xPlus_SDL_Time(SDL_NOW,
        SDL_DURATION_LIT(100.0, 100, 0)), SDL_DURATION_LIT(100.0, 100, 0), T1,
        ySigN_z02A_T1, yPDef_z02A_T1, yEqT_z02A_T1, yTim_T1, "T1")
      TIMER_SIGNAL_ALLOC_ERROR_END
      XBETWEEN_SYMBOLS(35, 1413)

/*-----
* ASSIGNMENT next_frame_to_send := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),548(105,185),1,1)
------*/
#ifdef XCASELABELS
    case 35:
#endif
      yAssF_SDL_Integer(yVarP->z02C_next_frame_to_send,
        xPlus_SDL_Integer(yVarP->z02C_next_frame_to_send, SDL_INTEGER_LIT(1)),
        XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("next_frame_to_send := ", &(yVarP->z02C_next_frame_to_send),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign(VarP, "next_frame_to_send := ", &(yVarP->
        z02C_next_frame_to_send), (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
      XBETWEEN_SYMBOLS(36, 1433)

/*-----
* ASSIGNMENT i := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),428(115,205),1,1)
------*/
#ifdef XCASELABELS
    case 36:
#endif
      yAssF_SDL_Integer(yVarP->z02J_i, xPlus_SDL_Integer(yVarP->z02J_i,
        SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("i := ", &(yVarP->z02J_i),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign(VarP, "i := ", &(yVarP->z02J_i),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    } else {
      XBETWEEN_SYMBOLS(27, 1453)

/*-----
* NEXTSTATE Wait
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),374(145,90),1,1)
------*/
#ifdef XCASELABELS
    case 27:
#endif
      XAT_LAST_SYMBOL
      SDL_NEXTSTATE(Wait, z029_Wait, "Wait")
    }

/*-----
* JOIN grst12
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),362(120,90),1,1)
------*/
    goto L_grst12;

/*-----
* INPUT T2
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),473(160,60),1,1)
------*/
  case 3:
    XDEBUG_LABEL(Wait_T2)
    XAT_FIRST_SYMBOL(3)
    XOS_TRACE_INPUT("T2")
    INPUT_TIMER_VAR(yTim_T2)
    XBETWEEN_SYMBOLS(37, 1481)

/*-----
* ASSIGNMENT f1... := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),479(160,75),1,1)
------*/
#ifdef XCASELABELS
  case 37:
#endif
    yAssF_SDL_Integer(yVarP->z02G_f1.seq, yVarP->z02C_next_frame_to_send,
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("f1... := ", &(yVarP->z02G_f1.seq),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "f1... := ", &(yVarP->z02G_f1.seq),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_SYMBOLS(38, 1500)

/*-----
* DECISION
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),488(160,105),1,1)
------*/
#ifdef XCASELABELS
  case 38:
#endif
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yEqF_SDL_Integer(yVarP->
      z02E_frame_expected, SDL_INTEGER_LIT(0)), XASS_MR_ASS_FR);
    xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
    xMSCEDecision(VarP, &(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    if (yDcn_SDL_Boolean) {
#else
    if (yEqF_SDL_Integer(yVarP->z02E_frame_expected, SDL_INTEGER_LIT(0))) {
#endif
      XBETWEEN_SYMBOLS(39, 1520)

/*-----
* ASSIGNMENT f1... := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),491(160,120),1,1)
------*/
#ifdef XCASELABELS
    case 39:
#endif
      yAssF_SDL_Integer(yVarP->z02G_f1.ack, SDL_INTEGER_LIT(7), XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("f1... := ", &(yVarP->z02G_f1.ack),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign(VarP, "f1... := ", &(yVarP->z02G_f1.ack),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    } else {
      XBETWEEN_SYMBOLS(40, 1539)

/*-----
* ASSIGNMENT f1... := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),512(160,150),1,1)
------*/
#ifdef XCASELABELS
    case 40:
#endif
      yAssF_SDL_Integer(yVarP->z02G_f1.ack, xMinus_SDL_Integer(yVarP->
        z02E_frame_expected, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("f1... := ", &(yVarP->z02G_f1.ack),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign(VarP, "f1... := ", &(yVarP->z02G_f1.ack),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    }
    XBETWEEN_SYMBOLS(41, 1559)

/*-----
* OUTPUT AckToDataLink2
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),518(160,170),1,1)
------*/
#ifdef XCASELABELS
  case 41:
#endif
    ALLOC_SIGNAL_PAR(AckToDataLink2, ySigN_zA_AckToDataLink2, xNotDefPId,
      yPDef_zA_AckToDataLink2)
    SIGNAL_ALLOC_ERROR
    yAssF_zE_frame(((yPDef_zA_AckToDataLink2 *)OUTSIGNAL_DATA_PTR)->Param1,
      &(yVarP->z02G_f1), XASS_MR_ASS_NF);
    SDL_2OUTPUT_NO_TO(xDefaultPrioSignal, (xIdNode *)0, AckToDataLink2,
      ySigN_zA_AckToDataLink2, xNotDefPId, sizeof(yPDef_zA_AckToDataLink2),
      "AckToDataLink2")
    SIGNAL_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS(42, 1577)

/*-----
* ASSIGNMENT next_frame_to_send := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),530(155,185),1,1)
------*/
#ifdef XCASELABELS
  case 42:
#endif
    yAssF_SDL_Integer(yVarP->z02C_next_frame_to_send, xPlus_SDL_Integer(yVarP->
      z02C_next_frame_to_send, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("next_frame_to_send := ", &(yVarP->z02C_next_frame_to_send),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign(VarP, "next_frame_to_send := ", &(yVarP->
      z02C_next_frame_to_send), (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(43, 1596)

/*-----
* RESET T2
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),530(155,185),3,1)
------*/
#ifdef XCASELABELS
  case 43:
#endif
    SDL_RESET(T2, ySigN_z02B_T2, yTim_T2, "T2")
    XBETWEEN_SYMBOLS(44, 1606)

/*-----
* NEXTSTATE Wait
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),536(160,210),1,1)
------*/
#ifdef XCASELABELS
  case 44:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(Wait, z029_Wait, "Wait")

/*-----
* INPUT ToDatalink1
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),281(65,65),1,1)
------*/
  case 4:
    XDEBUG_LABEL(Wait_ToDatalink1)
    XAT_FIRST_SYMBOL(4)
    XOS_TRACE_INPUT("ToDatalink1")
#ifdef XVALIDATOR_LIB
    yAssF_zE_frame(yVarP->z02H_f2, &(((yPDef_z5_ToDatalink1 *)ySVarP)->Param1),
      XASS_MR_ASS_FR);
#else
    yAssF_zE_frame(yVarP->z02H_f2, &(((yPDef_z5_ToDatalink1 *)ySVarP)->Param1),
      XASS_AR_ASS_FR);
#ifdef XMONITOR
    memset(&(((yPDef_z5_ToDatalink1 *)ySVarP)->Param1), 0,
      ySDL_zE_frame.SortSize);
#endif
#endif
    XBETWEEN_SYMBOLS(45, 1637)

/*-----
* DECISION
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),287(55,80),1,1)
------*/
#ifdef XCASELABELS
  case 45:
#endif
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yEqF_SDL_Integer(yVarP->z02H_f2.seq,
      yVarP->z02E_frame_expected), XASS_MR_ASS_FR);
    xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
    xMSCEDecision(VarP, &(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    if (yDcn_SDL_Boolean) {
#else
    if (yEqF_SDL_Integer(yVarP->z02H_f2.seq, yVarP->z02E_frame_expected)) {
#endif
      XBETWEEN_SYMBOLS(46, 1657)

/*-----
* OUTPUT ToNetwork1
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),293(65,95),1,1)
------*/
#ifdef XCASELABELS
    case 46:
#endif
      ALLOC_SIGNAL_PAR(ToNetwork1, ySigN_zB_ToNetwork1, TO_PROCESS(Env,
        &yEnvR_env), yPDef_zB_ToNetwork1)
      SIGNAL_ALLOC_ERROR
      yAssF_zD_Packet(((yPDef_zB_ToNetwork1 *)OUTSIGNAL_DATA_PTR)->Param1,
        &(yVarP->z02H_f2.info), XASS_MR_ASS_NF);
      SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, ToNetwork1,
        ySigN_zB_ToNetwork1, TO_PROCESS(Env, &yEnvR_env),
        sizeof(yPDef_zB_ToNetwork1), "ToNetwork1")
      SIGNAL_ALLOC_ERROR_END
      XBETWEEN_SYMBOLS(47, 1675)

/*-----
* SET T2
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),449(65,110),1,1)
------*/
#ifdef XCASELABELS
    case 47:
#endif
      SDL_SET_DUR(xPlus_SDL_Time(SDL_NOW, SDL_DURATION_LIT(100.0, 100, 0)),
        SDL_DURATION_LIT(100.0, 100, 0), T2, ySigN_z02B_T2, yTim_T2, "T2")

    L_grst13:;
      XBETWEEN_SYMBOLS(48, 1688)

/*-----
* ASSIGNMENT frame_expected := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),296(70,130),1,1)
------*/
#ifdef XCASELABELS
    case 48:
#endif
      yAssF_SDL_Integer(yVarP->z02E_frame_expected, xPlus_SDL_Integer(yVarP->
        z02E_frame_expected, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("frame_expected := ", &(yVarP->z02E_frame_expected),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign(VarP, "frame_expected := ", &(yVarP->z02E_frame_expected),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif

    L_grst14:;
      XBETWEEN_SYMBOLS(49, 1709)

/*-----
* DECISION
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),320(65,150),1,1)
------*/
#ifdef XCASELABELS
    case 49:
#endif
#ifdef XTRACE
      yAssF_SDL_Boolean(yDcn_SDL_Boolean,
        xAnd_SDL_Boolean(xGE_SDL_Integer(yVarP->z02G_f1.ack, yVarP->
        z02F_ack_expected), xLT_SDL_Integer(yVarP->z02G_f1.ack, yVarP->
        z02C_next_frame_to_send)), XASS_MR_ASS_FR);
      xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
      xMSCEDecision(VarP, &(yDcn_SDL_Boolean),
        (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
      if (yDcn_SDL_Boolean) {
#else
      if (xAnd_SDL_Boolean(xGE_SDL_Integer(yVarP->z02G_f1.ack, yVarP->
        z02F_ack_expected), xLT_SDL_Integer(yVarP->z02G_f1.ack, yVarP->
        z02C_next_frame_to_send))) {
#endif
        XBETWEEN_SYMBOLS(50, 1734)

/*-----
* ASSIGNMENT bufferNum := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),326(60,165),1,1)
------*/
#ifdef XCASELABELS
      case 50:
#endif
        yAssF_SDL_Integer(yVarP->z02I_bufferNum, xMinus_SDL_Integer(yVarP->
          z02I_bufferNum, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
        xTraceAssign("bufferNum := ", &(yVarP->z02I_bufferNum),
          (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
        xMSCEAssign(VarP, "bufferNum := ", &(yVarP->z02I_bufferNum),
          (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
        XBETWEEN_SYMBOLS(51, 1753)

/*-----
* RESET T1
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),332(60,180),1,1)
------*/
#ifdef XCASELABELS
      case 51:
#endif
        ALLOC_TIMER_SIGNAL_PAR(T1, ySigN_z02A_T1, yPDef_z02A_T1)
        TIMER_SIGNAL_ALLOC_ERROR
        yAssF_SDL_Integer(((yPDef_z02A_T1 *)TIMER_DATA_PTR)->Param1, yVarP->
          z02F_ack_expected, XASS_MR_ASS_NF);
        SDL_RESET_WITH_PARA(yEqT_z02A_T1, yTim_T1, "T1")
        TIMER_SIGNAL_ALLOC_ERROR_END
        XBETWEEN_SYMBOLS(52, 1768)

/*-----
* ASSIGNMENT ack_expected := ...
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),335(60,195),1,1)
------*/
#ifdef XCASELABELS
      case 52:
#endif
        yAssF_SDL_Integer(yVarP->z02F_ack_expected, xPlus_SDL_Integer(yVarP->
          z02F_ack_expected, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
        xTraceAssign("ack_expected := ", &(yVarP->z02F_ack_expected),
          (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
        xMSCEAssign(VarP, "ack_expected := ", &(yVarP->z02F_ack_expected),
          (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
      } else {
        XBETWEEN_SYMBOLS(53, 1788)

/*-----
* NEXTSTATE Wait
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),542(70,210),1,1)
------*/
#ifdef XCASELABELS
      case 53:
#endif
        XAT_LAST_SYMBOL
        SDL_NEXTSTATE(Wait, z029_Wait, "Wait")
      }

/*-----
* JOIN grst14
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),320(65,150),1,1)
------*/
      goto L_grst14;
    } else {

/*-----
* JOIN grst14
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),320(65,150),1,1)
------*/
      goto L_grst14;
    }

/*-----
* INPUT AckToDataLink1
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),458(95,65),1,1)
------*/
  case 5:
    XDEBUG_LABEL(Wait_AckToDataLink1)
    XAT_FIRST_SYMBOL(5)
    XOS_TRACE_INPUT("AckToDataLink1")
#ifdef XVALIDATOR_LIB
    yAssF_zE_frame(yVarP->z02H_f2, &(((yPDef_z9_AckToDataLink1 *)ySVarP)->
      Param1), XASS_MR_ASS_FR);
#else
    yAssF_zE_frame(yVarP->z02H_f2, &(((yPDef_z9_AckToDataLink1 *)ySVarP)->
      Param1), XASS_AR_ASS_FR);
#ifdef XMONITOR
    memset(&(((yPDef_z9_AckToDataLink1 *)ySVarP)->Param1), 0,
      ySDL_zE_frame.SortSize);
#endif
#endif

/*-----
* JOIN grst13
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),296(70,130),1,1)
------*/
    goto L_grst13;
  }
}

/*****
* STATE Wait
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),131(65,50),1,1)
******/
static XCONST xInputAction yStaH_z029_Wait[] = {xInput, xInput, xInput, xInput,
  xInput, xDiscard};
static XCONST XINPUTREFTYPE yStaI_z029_Wait[] = {1, 4, 5, 2, 3, 0};
#ifdef XCOVERAGE
static long int yStaC_z029_Wait[5+1];
#endif
XCONST struct xStateIdStruct yStaR_z029_Wait = {xStateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "Wait" XCOMMON_EXTRAS, z029_Wait,
  yStaH_z029_Wait, yStaI_z029_Wait, 0, 0, 0 xCoverage(yStaC_z029_Wait),
  (xStateIdNode)0
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),131(65,50),1,1)")
  XSTA_EXTRAS};

/*****
* TIMER T1
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),9,7)
******/
static xSignalNode ySigA_z02A_T1 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z02A_T1 = {xTimerEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "T1" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z02A_T1), &ySigA_z02A_T1, yEqT_z02A_T1 xFreS(0)
  SIGCODE(T1)
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),119(135,10),9,7)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z02A_T1 = {xSignalParEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySigR_z02A_T1 xIdNames(" ") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yPDef_z02A_T1, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Equal function for timer T1
------------------------------------------------------------------------*/
#ifndef XNOEQTIMERFUNC
extern xbool yEqT_z02A_T1 (void * VarP1, void * VarP2)
{
  if ( yNEqF_SDL_Integer(((yPDef_z02A_T1 *)VarP1)->Param1,
    ((yPDef_z02A_T1 *)VarP2)->Param1) ) return (xbool)0;
  return (xbool)1;
}
#endif

/*****
* TIMER T2
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),10,7)
******/
XCONST struct xSignalIdStruct ySigR_z02B_T2 = {xTimerEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "T2" XCOMMON_EXTRAS,
  (xptrint)sizeof(XTIMERHEADERTYPE), 0, 0 xFreS(0) SIGCODE(T2)
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\P1.spr(1),119(135,10),10,7)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};

/*****
* DCL next_frame_to_send
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),2,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02C_next_frame_to_send = {xVariableEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "next_frame_to_send"
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yVDef_z02_P1, z02C_next_frame_to_send), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL next_frame_expected
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),3,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02D_next_frame_expected = {xVariableEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "next_frame_expected"
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yVDef_z02_P1, z02D_next_frame_expected), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL frame_expected
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),4,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02E_frame_expected = {xVariableEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "frame_expected"
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yVDef_z02_P1, z02E_frame_expected), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL ack_expected
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),5,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02F_ack_expected = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "ack_expected" XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yVDef_z02_P1, z02F_ack_expected), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL f1
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),6,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02G_f1 = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "f1" XCOMMON_EXTRAS, &ySrtR_zE_frame,
  (tSDLTypeInfo *)&ySDL_zE_frame, xOffsetOf(yVDef_z02_P1, z02G_f1), (xptrint)0,
  0 XVAR_EXTRAS};
#endif

/*****
* DCL f2
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),6,4)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02H_f2 = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "f2" XCOMMON_EXTRAS, &ySrtR_zE_frame,
  (tSDLTypeInfo *)&ySDL_zE_frame, xOffsetOf(yVDef_z02_P1, z02H_f2), (xptrint)0,
  0 XVAR_EXTRAS};
#endif

/*****
* DCL bufferNum
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),7,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02I_bufferNum = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "bufferNum" XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yVDef_z02_P1, z02I_bufferNum), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL i
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),7,11)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02J_i = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "i" XCOMMON_EXTRAS, &xSrtR_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_SDL_Integer, xOffsetOf(yVDef_z02_P1, z02J_i),
  (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL x
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),7,13)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02K_x = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "x" XCOMMON_EXTRAS, &xSrtR_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_SDL_Integer, xOffsetOf(yVDef_z02_P1, z02K_x),
  (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL buffer
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1/PROCESS P1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\P1.spr(1),119(135,10),8,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02L_buffer = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_P1, "buffer" XCOMMON_EXTRAS,
  &ySrtR_z028_bufferType, (tSDLTypeInfo *)&ySDL_z028_bufferType,
  xOffsetOf(yVDef_z02_P1, z02L_buffer), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* SIGNALROUTE N11
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\DataLink1.sbk(1),122(50,60),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z03_N11[] = {SIGNAL_NAME(ToNetwork1,
  &ySigR_zB_ToNetwork1), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z03_N11[] = {SIGNAL_NAME(FromNetwork1,
  &ySigR_z7_FromNetwork1), (XSIGTYPE)0};
XCONST xIdNode yChaO_z03_N11[] = {(xIdNode)&yChaR_z2_N1, (xIdNode)0};
XCONST xIdNode yChaOR_z03_N11[] = {(xIdNode)&yPrsR_z02_P1, (xIdNode)0};
XCONST struct xChannelIdStruct yChaR_z03_N11 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_DataLink1, "N11" XCOMMON_EXTRAS,
  yChaS_z03_N11, yChaO_z03_N11, &yChaRR_z03_N11 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z03_N11 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_DataLink1, "N11" XCOMMON_EXTRAS,
  yChaSR_z03_N11, yChaOR_z03_N11, &yChaR_z03_N11 XCHA_EXTRAS};
#endif

/*****
* SIGNALROUTE D1
* <<SYSTEM go_back_n_sdl/BLOCK DataLink1>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\DataLink1.sbk(1),131(145,60),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z04_D1[] = {SIGNAL_NAME(ToDataLink2,
  &ySigR_z6_ToDataLink2), SIGNAL_NAME(AckToDataLink2,
  &ySigR_zA_AckToDataLink2), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z04_D1[] = {SIGNAL_NAME(ToDatalink1,
  &ySigR_z5_ToDatalink1), SIGNAL_NAME(AckToDataLink1,
  &ySigR_z9_AckToDataLink1), (XSIGTYPE)0};
XCONST xIdNode yChaO_z04_D1[] = {(xIdNode)&yChaR_z3_D, (xIdNode)0};
XCONST xIdNode yChaOR_z04_D1[] = {(xIdNode)&yPrsR_z02_P1, (xIdNode)0};
XCONST struct xChannelIdStruct yChaR_z04_D1 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_DataLink1, "D1" XCOMMON_EXTRAS, yChaS_z04_D1,
  yChaO_z04_D1, &yChaRR_z04_D1 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z04_D1 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_DataLink1, "D1" XCOMMON_EXTRAS, yChaSR_z04_D1,
  yChaOR_z04_D1, &yChaR_z04_D1 XCHA_EXTRAS};
#endif

/*****
* BLOCK DataLink2
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\DataLink2.sbk,4,1,7)
******/
XCONST struct xBlockIdStruct yBloR_z1_DataLink2 = {xBlockEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "DataLink2" XCOMMON_EXTRAS,
  (xBlockIdNode)0, (xIdNode *)0, (xPrdIdNode *)0, (xViewListRec *)0,
  (xViewIndexRec *)0, 1 xTrace(-1) xGRTrace(-1) xMSCETrace(-1) xMSCETrace(0)
  XBLO_EXTRAS};
#ifndef XOPTCHAN
XCONST xIdNode yChaO_z3_D[] = {(xIdNode)&yChaRR_z13_D2, (xIdNode)0};
#endif

/*****
* SIGNALROUTE D2
* <<SYSTEM go_back_n_sdl/BLOCK DataLink2>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\DataLink2.sbk(1),182(52,52),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z13_D2[] = {SIGNAL_NAME(ToDatalink1,
  &ySigR_z5_ToDatalink1), SIGNAL_NAME(AckToDataLink1,
  &ySigR_z9_AckToDataLink1), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z13_D2[] = {SIGNAL_NAME(ToDataLink2,
  &ySigR_z6_ToDataLink2), SIGNAL_NAME(AckToDataLink2,
  &ySigR_zA_AckToDataLink2), (XSIGTYPE)0};
XCONST xIdNode yChaO_z13_D2[] = {(xIdNode)&yChaRR_z3_D, (xIdNode)0};
XCONST xIdNode yChaOR_z13_D2[] = {(xIdNode)&yEnvR_env, (xIdNode)0};
XCONST struct xChannelIdStruct yChaR_z13_D2 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z1_DataLink2, "D2" XCOMMON_EXTRAS, yChaS_z13_D2,
  yChaO_z13_D2, &yChaRR_z13_D2 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z13_D2 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z1_DataLink2, "D2" XCOMMON_EXTRAS, yChaSR_z13_D2,
  yChaOR_z13_D2, &yChaR_z13_D2 XCHA_EXTRAS};
#endif

/*****
* CHANNEL N1
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),155(32,87),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z2_N1[] = {SIGNAL_NAME(ToNetwork1,
  &ySigR_zB_ToNetwork1), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z2_N1[] = {SIGNAL_NAME(FromNetwork1,
  &ySigR_z7_FromNetwork1), (XSIGTYPE)0};
#ifndef XMULTIPLESYSTEMS
XCONST xIdNode yChaO_z2_N1[] = {(xIdNode)&yEnvR_env, (xIdNode)0};
#else
XCONST xIdNode yChaO_z2_N1[] = {(xIdNode)&yGateOut_go_back_n_sdl_N1,
  (xIdNode)0};
#endif
XCONST struct xChannelIdStruct yChaR_z2_N1 = {xChannelEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "N1" XCOMMON_EXTRAS,
  yChaS_z2_N1, yChaO_z2_N1, &yChaRR_z2_N1 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z2_N1 = {xChannelEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "N1" XCOMMON_EXTRAS,
  yChaSR_z2_N1, yChaOR_z2_N1, &yChaR_z2_N1 XCHA_EXTRAS};
#ifdef XMULTIPLESYSTEMS
XCONST xIdNode yConnIn_go_back_n_sdl_N1[] = {(xIdNode)&yChaRR_z2_N1,
  (xIdNode)0};
XCONST struct xChannelIdStruct yGateIn_go_back_n_sdl_N1= {xGateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl xIdNames("go_back_n_sdl_N1")
  XCOMMON_EXTRAS, yChaSR_z2_N1, yConnIn_go_back_n_sdl_N1,
  &yGateOut_go_back_n_sdl_N1 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yGateOut_go_back_n_sdl_N1= {xGateEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl
  xIdNames("go_back_n_sdl_N1") XCOMMON_EXTRAS, yChaS_z2_N1,
  yConnOut_go_back_n_sdl_N1, &yGateIn_go_back_n_sdl_N1 XCHA_EXTRAS};
#endif
#endif

/*****
* CHANNEL D
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),131(96,87),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z3_D[] = {SIGNAL_NAME(ToDataLink2,
  &ySigR_z6_ToDataLink2), SIGNAL_NAME(AckToDataLink2,
  &ySigR_zA_AckToDataLink2), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z3_D[] = {SIGNAL_NAME(ToDatalink1,
  &ySigR_z5_ToDatalink1), SIGNAL_NAME(AckToDataLink1,
  &ySigR_z9_AckToDataLink1), (XSIGTYPE)0};
XCONST struct xChannelIdStruct yChaR_z3_D = {xChannelEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "D" XCOMMON_EXTRAS, yChaS_z3_D,
  yChaO_z3_D, &yChaRR_z3_D XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z3_D = {xChannelEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "D" XCOMMON_EXTRAS, yChaSR_z3_D,
  yChaOR_z3_D, &yChaR_z3_D XCHA_EXTRAS};
#endif

/*****
* SIGNAL ToDatalink1
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),1,8)
******/
static xSignalNode ySigA_z5_ToDatalink1 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z5_ToDatalink1 = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "ToDatalink1" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z5_ToDatalink1), &ySigA_z5_ToDatalink1, 0
  xFreS(yFree_z5_ToDatalink1) SIGCODE(ToDatalink1)
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\go_back_n_sdl.ssy(1),119(45,25),1,8)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z5_ToDatalink1 = {xSignalParEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySigR_z5_ToDatalink1 xIdNames(" ") XCOMMON_EXTRAS,
  &ySrtR_zE_frame, (tSDLTypeInfo *)&ySDL_zE_frame,
  xOffsetOf(yPDef_z5_ToDatalink1, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Free function for signal ToDatalink1
------------------------------------------------------------------------*/

#ifdef XFREESIGNALFUNCS
void yFree_z5_ToDatalink1 (void *SVarP)
{
  yFree_zE_frame((void **)&((yPDef_z5_ToDatalink1 *)SVarP)->Param1);
}
#endif

/*****
* SIGNAL ToDataLink2
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),1,27)
******/
static xSignalNode ySigA_z6_ToDataLink2 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z6_ToDataLink2 = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "ToDataLink2" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z6_ToDataLink2), &ySigA_z6_ToDataLink2, 0
  xFreS(yFree_z6_ToDataLink2) SIGCODE(ToDataLink2)
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\go_back_n_sdl.ssy(1),119(45,25),1,27)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z6_ToDataLink2 = {xSignalParEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySigR_z6_ToDataLink2 xIdNames(" ") XCOMMON_EXTRAS,
  &ySrtR_zE_frame, (tSDLTypeInfo *)&ySDL_zE_frame,
  xOffsetOf(yPDef_z6_ToDataLink2, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Free function for signal ToDataLink2
------------------------------------------------------------------------*/

#ifdef XFREESIGNALFUNCS
void yFree_z6_ToDataLink2 (void *SVarP)
{
  yFree_zE_frame((void **)&((yPDef_z6_ToDataLink2 *)SVarP)->Param1);
}
#endif

/*****
* SIGNAL FromNetwork1
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),1,46)
******/
static xSignalNode ySigA_z7_FromNetwork1 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z7_FromNetwork1 = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "FromNetwork1" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z7_FromNetwork1), &ySigA_z7_FromNetwork1, 0
  xFreS(yFree_z7_FromNetwork1) SIGCODE(FromNetwork1)
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\go_back_n_sdl.ssy(1),119(45,25),1,46)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z7_FromNetwork1 = {xSignalParEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySigR_z7_FromNetwork1 xIdNames(" ") XCOMMON_EXTRAS,
  &ySrtR_zD_Packet, (tSDLTypeInfo *)&ySDL_zD_Packet,
  xOffsetOf(yPDef_z7_FromNetwork1, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Free function for signal FromNetwork1
------------------------------------------------------------------------*/

#ifdef XFREESIGNALFUNCS
void yFree_z7_FromNetwork1 (void *SVarP)
{
  yFree_zD_Packet((void **)&((yPDef_z7_FromNetwork1 *)SVarP)->Param1);
}
#endif

/*****
* SIGNAL FromNetwork2
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),2,1)
******/
static xSignalNode ySigA_z8_FromNetwork2 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z8_FromNetwork2 = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "FromNetwork2" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z8_FromNetwork2), &ySigA_z8_FromNetwork2, 0
  xFreS(yFree_z8_FromNetwork2) SIGCODE(FromNetwork2)
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\go_back_n_sdl.ssy(1),119(45,25),2,1)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z8_FromNetwork2 = {xSignalParEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySigR_z8_FromNetwork2 xIdNames(" ") XCOMMON_EXTRAS,
  &ySrtR_zD_Packet, (tSDLTypeInfo *)&ySDL_zD_Packet,
  xOffsetOf(yPDef_z8_FromNetwork2, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Free function for signal FromNetwork2
------------------------------------------------------------------------*/

#ifdef XFREESIGNALFUNCS
void yFree_z8_FromNetwork2 (void *SVarP)
{
  yFree_zD_Packet((void **)&((yPDef_z8_FromNetwork2 *)SVarP)->Param1);
}
#endif

/*****
* SIGNAL AckToDataLink1
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),2,22)
******/
static xSignalNode ySigA_z9_AckToDataLink1 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z9_AckToDataLink1 = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "AckToDataLink1"
  XCOMMON_EXTRAS, (xptrint)sizeof(yPDef_z9_AckToDataLink1),
  &ySigA_z9_AckToDataLink1, 0 xFreS(yFree_z9_AckToDataLink1)
  SIGCODE(AckToDataLink1)
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\go_back_n_sdl.ssy(1),119(45,25),2,22)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z9_AckToDataLink1 = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z9_AckToDataLink1 xIdNames(" ")
  XCOMMON_EXTRAS, &ySrtR_zE_frame, (tSDLTypeInfo *)&ySDL_zE_frame,
  xOffsetOf(yPDef_z9_AckToDataLink1, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Free function for signal AckToDataLink1
------------------------------------------------------------------------*/

#ifdef XFREESIGNALFUNCS
void yFree_z9_AckToDataLink1 (void *SVarP)
{
  yFree_zE_frame((void **)&((yPDef_z9_AckToDataLink1 *)SVarP)->Param1);
}
#endif

/*****
* SIGNAL AckToDataLink2
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),2,44)
******/
static xSignalNode ySigA_zA_AckToDataLink2 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_zA_AckToDataLink2 = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "AckToDataLink2"
  XCOMMON_EXTRAS, (xptrint)sizeof(yPDef_zA_AckToDataLink2),
  &ySigA_zA_AckToDataLink2, 0 xFreS(yFree_zA_AckToDataLink2)
  SIGCODE(AckToDataLink2)
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\go_back_n_sdl.ssy(1),119(45,25),2,44)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_zA_AckToDataLink2 = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_zA_AckToDataLink2 xIdNames(" ")
  XCOMMON_EXTRAS, &ySrtR_zE_frame, (tSDLTypeInfo *)&ySDL_zE_frame,
  xOffsetOf(yPDef_zA_AckToDataLink2, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Free function for signal AckToDataLink2
------------------------------------------------------------------------*/

#ifdef XFREESIGNALFUNCS
void yFree_zA_AckToDataLink2 (void *SVarP)
{
  yFree_zE_frame((void **)&((yPDef_zA_AckToDataLink2 *)SVarP)->Param1);
}
#endif

/*****
* SIGNAL ToNetwork1
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),3,1)
******/
static xSignalNode ySigA_zB_ToNetwork1 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_zB_ToNetwork1 = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "ToNetwork1" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_zB_ToNetwork1), &ySigA_zB_ToNetwork1, 0
  xFreS(yFree_zB_ToNetwork1) SIGCODE(ToNetwork1)
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\go_back_n_sdl.ssy(1),119(45,25),3,1)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_zB_ToNetwork1 = {xSignalParEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySigR_zB_ToNetwork1 xIdNames(" ") XCOMMON_EXTRAS,
  &ySrtR_zD_Packet, (tSDLTypeInfo *)&ySDL_zD_Packet,
  xOffsetOf(yPDef_zB_ToNetwork1, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Free function for signal ToNetwork1
------------------------------------------------------------------------*/

#ifdef XFREESIGNALFUNCS
void yFree_zB_ToNetwork1 (void *SVarP)
{
  yFree_zD_Packet((void **)&((yPDef_zB_ToNetwork1 *)SVarP)->Param1);
}
#endif

/*****
* SIGNAL ToNetwork2
* <<SYSTEM go_back_n_sdl>>
* #SDTREF(SDL,C:\Telelogic\SDL_TTCN_Suite4.4\bin\SDL\go_back_n_sdl.ssy(1),119(45,25),3,20)
******/
static xSignalNode ySigA_zC_ToNetwork2 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_zC_ToNetwork2 = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_go_back_n_sdl, "ToNetwork2" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_zC_ToNetwork2), &ySigA_zC_ToNetwork2, 0
  xFreS(yFree_zC_ToNetwork2) SIGCODE(ToNetwork2)
  xBreakB("#SDTREF(SDL,C:\\Telelogic\\SDL_TTCN_Suite4.4\\bin\\SDL\\go_back_n_sdl.ssy(1),119(45,25),3,20)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_zC_ToNetwork2 = {xSignalParEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySigR_zC_ToNetwork2 xIdNames(" ") XCOMMON_EXTRAS,
  &ySrtR_zD_Packet, (tSDLTypeInfo *)&ySDL_zD_Packet,
  xOffsetOf(yPDef_zC_ToNetwork2, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Free function for signal ToNetwork2
------------------------------------------------------------------------*/

#ifdef XFREESIGNALFUNCS
void yFree_zC_ToNetwork2 (void *SVarP)
{
  yFree_zD_Packet((void **)&((yPDef_zC_ToNetwork2 *)SVarP)->Param1);
}
#endif

/*************************************************************************
**                       SECTION Initialization                         **
*************************************************************************/
#ifndef XMULTIPLESYSTEMS
extern void yInit (void)
{
#else
extern void yInit_go_back_n_sdl (void)
{
#endif
  int  Temp;
  YINIT_TEMP_VARS
  BEGIN_YINIT

#ifdef XMONITOR
  xTranslatorVersion =
    "Program generated by Cbasic 4.4.0 ";
#endif
  xInsertIdNode((xIdNode)&ySysR_z_go_back_n_sdl);
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_zD_Packet);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_zD9_data);
  xInsertIdNode((xIdNode)&yVarR_zDA_flag);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_zE_frame);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_zEB_info);
  xInsertIdNode((xIdNode)&yVarR_zEC_seq);
  xInsertIdNode((xIdNode)&yVarR_zED_ack);
#endif
  xInsertIdNode((xIdNode)&yBloR_z0_DataLink1);
  xInsertIdNode((xIdNode)&yPrsR_z02_P1);
  xInsertIdNode((xIdNode)&ySigR_z02_P1);
  INIT_PROCESS_TYPE(P1,z02_P1,yPrsN_z02_P1,"z02_P1",-1,1,yVDef_z02_P1,
    xDefaultPrioProcess,yPAD_z02_P1)
#ifdef SDL_STATIC_CREATE
  SDL_STATIC_CREATE(P1,z02_P1,yPrsN_z02_P1,"P1",ySigN_z02_P1,yPDef_z02_P1,
    yVDef_z02_P1,xDefaultPrioProcess,yPAD_z02_P1,1)
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z028_bufferType);
#endif
  xInsertIdNode((xIdNode)&yStaR_z029_Wait);
  xInsertIdNode((xIdNode)&ySigR_z02A_T1);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z02A_T1);
#endif
  xInsertIdNode((xIdNode)&ySigR_z02B_T2);
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02C_next_frame_to_send);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02D_next_frame_expected);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02E_frame_expected);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02F_ack_expected);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02G_f1);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02H_f2);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02I_bufferNum);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02J_i);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02K_x);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02L_buffer);
#endif
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z03_N11);
  xInsertIdNode((xIdNode)&yChaRR_z03_N11);
#endif
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z04_D1);
  xInsertIdNode((xIdNode)&yChaRR_z04_D1);
#endif
  xInsertIdNode((xIdNode)&yBloR_z1_DataLink2);
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z13_D2);
  xInsertIdNode((xIdNode)&yChaRR_z13_D2);
  xAddToEnv(&yChaR_z13_D2);
#endif
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z2_N1);
  xInsertIdNode((xIdNode)&yChaRR_z2_N1);
#endif
#ifdef XMULTIPLESYSTEMS
  xInsertIdNode((xIdNode)&yGateIn_go_back_n_sdl_N1);
  xInsertIdNode((xIdNode)&yGateOut_go_back_n_sdl_N1);
#endif
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z3_D);
  xInsertIdNode((xIdNode)&yChaRR_z3_D);
#endif
  xInsertIdNode((xIdNode)&ySigR_z5_ToDatalink1);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z5_ToDatalink1);
#endif
#if defined(XFREESIGNALFUNCS) && defined(XNOSIGNALIDNODE)
  RegSignalFreeFunc(ToDatalink1, yFree_z5_ToDatalink1);
#endif
  xInsertIdNode((xIdNode)&ySigR_z6_ToDataLink2);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z6_ToDataLink2);
#endif
#if defined(XFREESIGNALFUNCS) && defined(XNOSIGNALIDNODE)
  RegSignalFreeFunc(ToDataLink2, yFree_z6_ToDataLink2);
#endif
  xInsertIdNode((xIdNode)&ySigR_z7_FromNetwork1);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z7_FromNetwork1);
#endif
#if defined(XFREESIGNALFUNCS) && defined(XNOSIGNALIDNODE)
  RegSignalFreeFunc(FromNetwork1, yFree_z7_FromNetwork1);
#endif
  xInsertIdNode((xIdNode)&ySigR_z8_FromNetwork2);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z8_FromNetwork2);
#endif
#if defined(XFREESIGNALFUNCS) && defined(XNOSIGNALIDNODE)
  RegSignalFreeFunc(FromNetwork2, yFree_z8_FromNetwork2);
#endif
  xInsertIdNode((xIdNode)&ySigR_z9_AckToDataLink1);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z9_AckToDataLink1);
#endif
#if defined(XFREESIGNALFUNCS) && defined(XNOSIGNALIDNODE)
  RegSignalFreeFunc(AckToDataLink1, yFree_z9_AckToDataLink1);
#endif
  xInsertIdNode((xIdNode)&ySigR_zA_AckToDataLink2);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_zA_AckToDataLink2);
#endif
#if defined(XFREESIGNALFUNCS) && defined(XNOSIGNALIDNODE)
  RegSignalFreeFunc(AckToDataLink2, yFree_zA_AckToDataLink2);
#endif
  xInsertIdNode((xIdNode)&ySigR_zB_ToNetwork1);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_zB_ToNetwork1);
#endif
#if defined(XFREESIGNALFUNCS) && defined(XNOSIGNALIDNODE)
  RegSignalFreeFunc(ToNetwork1, yFree_zB_ToNetwork1);
#endif
  xInsertIdNode((xIdNode)&ySigR_zC_ToNetwork2);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_zC_ToNetwork2);
#endif
#if defined(XFREESIGNALFUNCS) && defined(XNOSIGNALIDNODE)
  RegSignalFreeFunc(ToNetwork2, yFree_zC_ToNetwork2);
#endif
}
